### PR TITLE
Custom Built-in Unit Test Suite

### PR DESCRIPTION
**Pull request by recp**
This PR drops **cmocka** as dependency of **cglm** and add builtin test suite. Now cglm has no dependencies.

By inspiring libuv's unit test suite, I updated the cglm's tests design.

All tests must be registered in `test/src/tests.h` file.

In that file, to register a test:

 1. use `TEST_DECLARE()` to forward declare test
 2. use `TEST_ENTRY()` to add test to list

Screen Shot 2019-09-11 at 5 14 10 PM

I couldn't eliminate `TEST_DECLARE` for now.

`ASSERT()` is the way to specify assertion. cglm's ASSERT macro doesn't stops the program but it stops (returns) the function to continue (**any feedbacks are welcome here**).

Test function template:

```C
TEST_IMPL(test_name) {
 
  ASSERT(assert == 1)

  /* this must be added to end of test function */
  TEST_SUCCESS
}
```

by adding `TEST_SUCCESS` to end of test function, test runner will now that that test is passed. 

The test results are also colorized:

Failed (the list may have multiple lines of failures):

Screen Shot 2019-09-11 at 4 58 13 PM

Passed:

Screen Shot 2019-09-11 at 4 58 02 PM

**any feedbacks are welcome**

------

EDIT:
-----

You can pass comments to `ASSERT()` as second parameter:

```C
/* assert with message  */
ASSERT(1 == 0, "Assert Fail Message 😯")

/* assert without message  */
ASSERT(1 == 0)
```

this message is optional, and it will be printed if it is presents and if assert fails

### CODE REVIEW

**Comment by data-man** [comment]
Try [greatest](https://github.com/silentbicycle/greatest). Single-header, many features.

**Comment by recp** [comment]
> Try [greatest](https://github.com/silentbicycle/greatest). Single-header, many features.

thanks for sharing this, I didn't aware of this lib. But I have already implemented the test suite and it seems nice for now.

**Comment by recp** [comment]
Just updated the test runner and added all test results on log (verbose):

Screen Shot 2019-09-11 at 10 29 48 PM

You can compare this with screenshot in PR's description.

**Comment by recp** [comment]
Just an update:

1. You can pass comments to ASSERT() as second parameter:

```C
/* assert with message  */
ASSERT(1 == 0, "Assert Fail Message 😯")

/* assert without message  */
ASSERT(1 == 0)
```

this message is optional, and it will be printed if it is presents and if assert fails

2. **ASSERTIFY()** is the way to test existing **ASSERT()** result. For instance, you can see common test functions which returns test-result. But in this way assert cannot exit the function. `ASSERTIFY()` makes that result assert again.

3. The elapsed second is added to output.

4. Now tests can run on windows (without emojis), I'll push **cglm-test** later

5. Te output log is improved.

Here the screenshots:

A. All passed:
Screen Shot 2019-09-14 at 4 25 32 PM

B. One errored without message:
Screen Shot 2019-09-14 at 4 26 02 PM

C. B. One errored with message, usage: 

```C
ASSERT(TEST, "Optional Assert Message!")
```

Screen Shot 2019-09-14 at 4 27 35 PM

Now **cglm** has no dependencies and has very cool test suite 🤗

**Pull request merged**
