### PR TITLE
Resolve vec4 : glm_vec4_distance() to satisfy compiling on armv7

### PR DESCRIPTION
**Pull request by haxpor**
Fixed according to @recp 's suggestion of solution at #82 .
Test cases are added.

Tested on PC (Linux ubuntu 18.04 with SSE/SSE2/SSE3/SSE4 capable).
Tested on real Android device (Android 6.0, aarch64).

### CODE REVIEW

**Comment by haxpor** [comment]
note I noticed 1 failed test result in bezier (pulled from the tip).

**Comment by recp** [comment]
Hi @haxpor 

Thanks for this PR.

I have added this to travis:

```yml
after_failure:
  - cat ./test-suite.log
```

we should see what is wrong in travis's logs now

**Comment by recp** [comment]
> note I noticed 1 failed test result in bezier (pulled from the tip).

this is weird, it passes on my local macos and macos on the travis-ci. My Linux VMs are not working for now, after fixed that I'll test it on Linux

**Comment by haxpor** [comment]
I pull down the tip from `fix_82` branch again. I got the same result as before.

```
[       OK ] test_vec4
[ RUN      ] test_vec3
[       OK ] test_vec3
[ RUN      ] test_affine
[       OK ] test_affine
[ RUN      ] test_bezier
[  ERROR   ] --- glm_eq(smc, Bs_plain)
[   LINE   ] --- test/src/test_bezier.c:54: error: Failure!
[  FAILED  ] test_bezier
[==========] 12 test(s) run.
[  PASSED  ] 11 test(s).
[  FAILED  ] 1 test(s), listed below:
[  FAILED  ] test_bezier

 1 FAILED TEST(S)
FAIL test/tests (exit status: 1)
```

**Comment by recp** [comment]
*SMC* is matrix and vector multiplication. So there may be rounding errors, because SIMD registers (SSE/AVX....) do not have enough precision like single FPU... I was used this:

```C
assert_true(glm_eq(smc, Bs_plain));
assert_true(glm_eq(Bs,  smc));
```

it must be:
```C
test_assert_eqf(smc, Bs_plain);
test_assert_eqf(Bs,  smc);
```

Now all tests are passed.

**Comment by recp** [comment]
@haxpor thanks for your contribution!

**Pull request merged**
