### PR TITLE
add some missing non-square matrix funcs

### PR DESCRIPTION
**Pull request by recp**
add missing functions for new non-square matrices:

- [x] copy
- [x] zero
- [x] mul
- [x] mulv
- [x] transpose
- [x] scale

### CODE REVIEW

**Comment by EasyIP2023** [comment]
@recp Do you need any help with this MR. I can write some docs for you.

**Comment by recp** [comment]
@EasyIP2023 thanks, it would be nice to have docs and tests yes ;)

**Comment by EasyIP2023** [comment]
@recp Question is `glm_mat2x3_transpose` supposed to be `glm_mat2x3_transpose_to`?

**Comment by EasyIP2023** [comment]
@recp Nevermind just thought about why

**Pull request merged**
