### PR TITLE
WIP: Wasm simd128 support

### PR DESCRIPTION
**Pull request by myfreeer**
See https://github.com/recp/cglm/discussions/282 for previous discussion.

TODOs
--------

- [x] Inline or rewrite sse2 wrappers borrowed from emscripten
    - [x] _mm_cvtss_f32
    - [x] _mm_movehl_ps
    - [x] _mm_movelh_ps
    - [x] _mm_sqrt_ss
    - [x] _mm_rcp_ps
    - [x] _mm_storeu_ps
    - [x] _mm_store_ss
    - [x] _MM_TRANSPOSE4_PS

- [x] Guard againist conditions when both `sse2` and `simd128` enabled by Emscripten (https://github.com/recp/cglm/pull/286#issuecomment-1492985403)
     - [x] affine-mat.h
     - [x] intrin.h
     - [x] mat2.h
     - [x] mat3.h
     - [x] mat4.h
     - [x] quat.h
     - [x] vec4-ext.h
     - [x] vec4.h

- [x] Change in compile scripts for cross-compiling or a build guide
    - [x] [cmake](https://github.com/recp/cglm/blob/master/CMakeLists.txt)
    - [~~autoconf~~](https://github.com/recp/cglm/blob/master/configure.ac) [delayed](https://github.com/recp/cglm/pull/286#issuecomment-1517840171) since it could take too lang
    - [~~meson~~](https://github.com/recp/cglm/blob/master/meson.build) [delayed](https://github.com/recp/cglm/pull/286#issuecomment-1517840171) since it could take too lang

- [x] CI-driven tests, cross compile all tests with or without simd128,  using [appveyor](https://github.com/recp/cglm/blob/master/appveyor.yml) or [Github Actions](https://github.com/recp/cglm/issues/226)
     - [x] target: [wasi-sdk](https://github.com/WebAssembly/wasi-sdk)
     - [x] target: [wasi-sdk](https://github.com/WebAssembly/wasi-sdk) with simd128
     - [x] target: [emsdk](https://github.com/emscripten-core/emsdk)
     - [x] target: [emsdk](https://github.com/emscripten-core/emsdk) with simd128
     - [x] target: [emsdk](https://github.com/emscripten-core/emsdk) with sse2 and simd128
     - [x] runtime: [wasmtime](https://github.com/bytecodealliance/wasmtime)
     - [x] runtime: [wasmer](https://github.com/wasmerio/wasmer)

- [ ] [Code style](https://github.com/recp/cglm/blob/master/CONTRIBUTING.md) changes

Compiling
--------

Currently the tests can be cross-compiled to wasi using clang and [wasi-sdk](https://github.com/WebAssembly/wasi-sdk) with cmake arguments below:
```
-DCMAKE_C_FLAGS="-msimd128"
-DCMAKE_TOOLCHAIN_FILE=/path/to/wasi-sdk-19.0/share/cmake/wasi-sdk.cmake
-DWASI_SDK_PREFIX=/path/to/wasi-sdk-19.0
-DCGLM_USE_TEST=ON
```
Where `/path/to/wasi-sdk-19.0/` is the path to extracted wasi sdk.

The [cmake-wasm.yml](https://github.com/recp/cglm/pull/286/files#diff-7036d35aa720748ba23aa1efda334598dbe8a5d10a7698692daa7bc459bbbe44) shows an example for compiling and running tests on github actions.

### CODE REVIEW

**Comment by kzhsw** [comment]
The `_mm_storeu_ps` here is defined mostly like the build-in `wasm_v128_store`, and there two would compile to the same [result in clang](https://godbolt.org/z/WeKGrKrq5).

```c
static __inline__ void __attribute__((__always_inline__, __nodebug__))
_mm_storeu_ps(float *__p, glmm_128 __a)
{
  struct __unaligned {
    glmm_128 __v;
  } __attribute__((__packed__, __may_alias__));
  ((struct __unaligned *)__p)->__v = __a;
}

static __inline__ void __DEFAULT_FN_ATTRS wasm_v128_store(void *__mem,
                                                          v128_t __a) {
  // UB-free unaligned access copied from xmmintrin.h
  struct __wasm_v128_store_struct {
    __v128_u __v;
  } __attribute__((__packed__, __may_alias__));
  ((struct __wasm_v128_store_struct *)__mem)->__v = __a;
}

```

**Comment by gottfriedleibniz** [comment]
Another potential edge-case that may require handling is compiling w/ Emscripten, e.g., `emcc -msimd128 -msse -msse2 ...` which will enable both `CGLM_SIMD_x86` and `CGLM_SIMD_WASM`.

**Comment by myfreeer** [comment]
> Another potential edge-case that may require handling is compiling w/ Emscripten, e.g., `emcc -msimd128 -msse -msse2 ...` which will enable both `CGLM_SIMD_x86` and `CGLM_SIMD_WASM`.

This could be guarded by some extra check in macros like this, a lot more similar things should be changed.
```patch
diff --git a/include/cglm/simd/intrin.h b/include/cglm/simd/intrin.h 
index 17998f5..bf8d119 100644                                        
--- a/include/cglm/simd/intrin.h                                     
+++ b/include/cglm/simd/intrin.h                                     
@@ -113,7 +113,7 @@                                                  
 #  endif
 #endif

-#if defined(CGLM_SIMD_x86) 
+#if defined(CGLM_SIMD_x86) && !defined(CGLM_SIMD_WASM)
 #  include "x86.h"
 #endif

diff --git a/include/cglm/vec4.h b/include/cglm/vec4.h
index d6ee080..e90a3c3 100644
--- a/include/cglm/vec4.h
+++ b/include/cglm/vec4.h 
@@ -181,10 +181,10 @@ glm_vec4_ucopy(vec4 v, vec4 dest) {
 CGLM_INLINE
 void
 glm_vec4_zero(vec4 v) {
-#if defined( __SSE__ ) || defined( __SSE2__ )
-  glmm_store(v, _mm_setzero_ps());
-#elif defined(__wasm__) && defined(__wasm_simd128__)
+#if defined(__wasm__) && defined(__wasm_simd128__)
   glmm_store(v, wasm_f32x4_const_splat(0.f));
+#elif defined( __SSE__ ) || defined( __SSE2__ )
+  glmm_store(v, _mm_setzero_ps());
 #elif defined(CGLM_NEON_FP)
   vst1q_f32(v, vdupq_n_f32(0.0f));
 #else


```

**Comment by recp** [comment]
@myfreeer great work! any new progress?

**Comment by myfreeer** [comment]
> @myfreeer great work! any new progress?

Yes, github actions added for tests.

**Comment by recp** [comment]
@myfreeer awesome 🚀

**Comment by recp** [comment]
@myfreeer any new progress ? It would be nice to merge this asap

**Comment by myfreeer** [comment]
> @myfreeer any new progress ? It would be nice to merge this asap

@recp
No, I was planning for support of autoconf and meson support, autotools failed to [build tests](https://github.com/myfreeer/cglm/actions/runs/4711112383/jobs/8355277666), and meson needs some cross-file with absolute path, some extra helper scripts might be needed for generating this. Maybe we should delay supporting those (maybe in another pr), and mark this as ready-for-review.
BTW, which tool is suitable for [code style](https://github.com/recp/cglm/blob/master/CONTRIBUTING.md) checking?

**Comment by recp** [comment]
>  No, I was planning for support of autoconf and meson support, autotools failed to [build tests](https://github.com/myfreeer/cglm/actions/runs/4711112383/jobs/8355277666), and meson needs some cross-file with absolute path, some extra helper scripts might be needed for generating this, meson would [fail](https://github.com/myfreeer/cglm/actions/runs/4765052934) to build tests with maybe the https://github.com/mesonbuild/meson/issues/10187 issue. Maybe we should delay supporting those (maybe in another pr), and mark this as ready-for-review.

@myfreeer yes this is good approach I think. This PR became huge update, another PR[s] would be awesome, I hope we won't forget it :)

> BTW, which tool is suitable for [code style](https://github.com/recp/cglm/blob/master/CONTRIBUTING.md) checking?

🤷‍♂️ if it will take long time, I or you could do it later

**Comment by recp** [comment]
@myfreeer the PR is merged 🚀 many thanks. Feel free to create PRs for additional improvements

**Comment by myfreeer** [comment]
Great! Also, it seems that the github actions ci needs to be manually enabled in this repo to make it work.

**Comment by recp** [comment]
I have just enabled the actions 👍

**Pull request merged**
