### PR TITLE
meson: don't build by default if used in a subproject

### PR DESCRIPTION
**Pull request by v1993**
This allows to do the following in a project using cglm as a subproject and avoid building cglm's standalone library if you only use inline versions of functions:

```meson
cglm_dep = dependency(
  'cglm',
  default_options: [ 'install=false' ]
).partial_dependency(
  compile_args: true,
  includes: true,
)

# Needed since it's won't be pulled in automatically now
libm_dep = meson.get_compiler('c').find_library('m', required: false)
```

### CODE REVIEW

**Comment by recp** [comment]
@v1993 thanks for your contributions, 

Should we add this to meson section of README, Docs to let users know how to use inline-only version of **cglm** ?

**Comment by v1993** [comment]
I think a note in readme would be nice, yes. This works with system-wide cglm as well.

**Comment by kzhsw** [comment]
[CI ](https://github.com/recp/cglm/actions/runs/7070293843/job/19246847085) seems broken, any idea?
> meson.build:93:11: ERROR: declare_dependency got unknown keyword arguments "build_by_default"

**Comment by v1993** [comment]
> [CI ](https://github.com/recp/cglm/actions/runs/7070293843/job/19246847085) seems broken, any idea?
> 
> > meson.build:93:11: ERROR: declare_dependency got unknown keyword arguments "build_by_default"

That's what I get for making this PR from web interface and not double-checking :facepalm:. The new line was supposed to go in `library` call just above, not `declare_dependency`.

**Comment by recp** [comment]
https://github.com/recp/cglm/commit/abb71a8e32ff56314ce70edc0bb92b332efb704a should fix the issue, @v1993 right?

**Comment by v1993** [comment]
> [abb71a8](https://github.com/recp/cglm/commit/abb71a8e32ff56314ce70edc0bb92b332efb704a) should fix the issue, @v1993 right?

Yep, that seems to be correct. Thanks for getting this sorted out!

**Comment by recp** [comment]
@v1993 thanks 👍

**Pull request merged**
