### PR TITLE
eqv, eq, fill for ivec2 and ivec3, documentation fixes

### PR DESCRIPTION
**Pull request by duarm**
- New `glm_ivec4_print`, `glm_ivec2_print` functions
- New `eqv`, `eq`, `fill` functions for `ivec3` and `ivec2`
- Adding missing `glm_vec2_print` to the docs.
- Adding missing call func `glmc_vec2_fill`, `glmc_vec2_eq`, `glmc_vec2_eqv`
- Changed wording on the print documention to a generic "vector" and "matrix" instead of the type, to be more inline with how it's worded everywhere else.

### CODE REVIEW

**Comment by recp** [comment]
@duarm the PR is merged, thanks for your contributions 🚀 It would be nice to have ivec4 versions of the new functions :)

**Comment by gottfriedleibniz** [comment]
Would it be possible to update `glm_ivec2_fill` and `glm_ivec3_fill` to explicitly cast those values? For example, compiling with MSVC `/W2` (or above) will throw:

```
cglm\include\cglm\ivec2.h(219,17): warning C4244: '=': conversion from 'float' to 'int', possible loss of data 
cglm\include\cglm\ivec3.h(227,24): warning C4244: '=': conversion from 'float' to 'int', possible loss of data 
```

**Comment by recp** [comment]
@gottfriedleibniz wow my mistake, those parameters must be int as base type of vector, it is fixed at: https://github.com/recp/cglm/commit/126f809dae76d51f1527cf19627d7c08b02ed108

**Comment by gottfriedleibniz** [comment]
If that's the case, `glmc_ivec{2,3}_fill` also require updating.

**Comment by recp** [comment]
done :)

**Comment by duarm** [comment]
missed that too, sorry

**Pull request merged**
