### PR TITLE
adding glm_vec2_center

### PR DESCRIPTION
**Pull request by duarm**
new glm_vec2_center function, there's already a vec3 version, this will be useful for when we implement 2d aabb

### CODE REVIEW

**Comment by recp** [comment]
Hi @duarm,

Thanks, is it possible to add this function to struct api (include/cglm/struct/) and docs/ too, otherwise I'll do it later after merge the PR.

**Comment by duarm** [comment]
I can do it no prob

**Comment by duarm** [comment]
done, I've already added the docs to docs/source/vec2.rst, couldn't find a docs for the struct api, if there is such a thing

**Comment by recp** [comment]
@duarm many thanks, the PR is merged 🚀

> couldn't the struct api docs, if there is such a thing

Since it is same job, there is no need to duplicate docs

**Pull request merged**
