### PR TITLE
ivec += and -= functions

### PR DESCRIPTION
**Pull request by BeeverFeever**
@recp This first commit is purely just to make sure the format and style is what you were thinking of for the ivec functions. I noticed the += family of functions weren't even there so I implemented them as well. This is all I have done, I haven't bothered with tests yet, I am just seeking your feedback on any details before I implement them for ivec3 and ivec4 (and also finish ivec2). There may be errors in here but I will read over it all when I polish it up.

### CODE REVIEW

**Comment by recp** [comment]
@BeeverFeever ping.

**Comment by BeeverFeever** [comment]
@recp Hey, sorry for the wait. I havent been home for a while so I havent been able to do anything. Im getting home tomorrow today though. I should be able to have it almost done by tomorrow.

**Comment by recp** [comment]
@BeeverFeever thanks 🤗

**Comment by BeeverFeever** [comment]
@recp Just finished them (atleast I think everything is done).

**Comment by recp** [comment]
@BeeverFeever many thanks for your contributions, the PR is merged 🚀

**Pull request merged**
