### PR TITLE
ci: Remove appveyor.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is now handled by the GitHub Actions CI.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
image

I think you want to remove those 3 somehow.

**Comment by recp** [comment]
@waywardmonkeys thanks for your contributions, the PR is merged 🚀

> I think you want to remove those 3 somehow.

Travis should be dropped but I think Codacy or better alternatives can still exist to be aware of code quality. Measuring coverage is also crucial because engines, games, apps... will use math and all lines, operations must be tested well on all available platforms with all possible configuration e.g. SSE, AVX, NEON...

**Comment by waywardmonkeys** [comment]
@recp Yes, it is good to have them, but they aren't working / configured. Can add codacy back if it is set up later rather than have CI runs marked as having pending tasks. Appveyor stuff is now marking checks as having failed for commits to master.

**Comment by recp** [comment]
@waywardmonkeys I have just removed Travis-CI, AppVeyor and Codacy webhooks, will try to make Codacy work later then can be added later.

**Pull request merged**
