### PR TITLE
add new matrix mat2x3

### PR DESCRIPTION
**Pull request by EasyIP2023**
Initial function being

`glm_mat2x3_make`

### CODE REVIEW

**Comment by EasyIP2023** [comment]
Adding here still working progress. @recp

**Comment by EasyIP2023** [comment]
Able to rebase and run into wasm-ld error when linking tests working on understanding why now

**Comment by EasyIP2023** [comment]
Hey, @recp should be ready for review. Believe I covered everything.

**Comment by recp** [comment]
@EasyIP2023 thanks for your contributions, the PR is merged now 🚀

**Pull request merged**
