### PR TITLE
vec2 and mat2 support

### PR DESCRIPTION
**Pull request by recp**
This PR provides new vector and matrix size. Some mat2 operations supports SIMD (because it may not worth to implement SIMD for all operations, currently **cglm** supports SIMD if it makes that operation faster than plain/raw implementation)

There are a few TODOs before merge this PR:

- [x] rotate `vec2` by angle and axis
- [x] struct support for vec2 and mat2
- [x] some tests
- [ ] documentation
- [ ] more to come

### CODE REVIEW

**Comment by jdolan** [comment]
Are you looking for help with this one? I would really love to have vec2 :)

**Comment by recp** [comment]
Hi @jdolan 

> Are you looking for help with this one? I would really love to have vec2 :)

Sure, thanks, contribution is always welcome. I just couldn't have enough free time these days, I have lot of projects... 

It would be very awesome to get a review and feedbacks about this PR (and other PRs of course).

**Comment by recp** [comment]
I'm going to merge this PR. Any other features or bug fixes can be added later.

**Comment by recp** [comment]
@jdolan this PR is merged now, new release of **cglm** is on the way.

**Comment by jdolan** [comment]
That's awesome @recp. I ended up baking my own ghetto little math library inside of Quetoo, but I may revisit this eventually and use cglm everywhere.

**Comment by recp** [comment]
Thanks @jdolan 

This is the release: https://github.com/recp/cglm/releases/tag/v0.7.0

Since vec2 and mat2 are new features, bugs may occurs. Any feedback or help would be appreciated.

Also there are some missing functions for vec2 (e.g. rotate around point, center, project...), they will be added soon, plus some operations will be optimized with SIMD later, especially mat2. I have tried to write tests for them but they are basic/simple... More complicated tests must be written in the future. 

FWIW, we can fix bugs or improve things quickly, I'm trying my best as possible as I can.

**Pull request merged**
